config/routes.rb
Rails.application.routes.draw do
  resources :ride_offer_comments
  resources :forum_comments
  resources :forums
  resources :ride_offers
  resources :recent_change_comments
  resources :recent_changes
  resources :profile_contents
  resources :profile_contents
  resources :profile_contents
  resources :about_us
  resources :information
  resources :information
  resources :sponsors
  resources :profiles
  resources :friends
  resources :comments
  resources :ideas
  root to: 'visitors#index'
  devise_for :users
  resources :users

end

app/models/about_u.rb
class AboutU < ActiveRecord::Base
  validates_format_of :phone, :with => /\d{8}/, :message => " of phone must be phone number"
  validates_presence_of :name
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  before_action :set_about_u, only: [:show, :edit, :update, :destroy]

  # GET /about_us
  # GET /about_us.json
  def index
    @about_us = AboutU.all
  end

  # GET /about_us/1
  # GET /about_us/1.json
  def show
  end

  # GET /about_us/new
  def new
    @about_u = AboutU.new
  end

  # GET /about_us/1/edit
  def edit
  end

  # POST /about_us
  # POST /about_us.json
  def create
    @about_u = AboutU.new(about_u_params)

    respond_to do |format|
      if @about_u.save
        format.html { redirect_to @about_u, notice: 'About u was successfully created.' }
        format.json { render :show, status: :created, location: @about_u }
      else
        format.html { render :new }
        format.json { render json: @about_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /about_us/1
  # PATCH/PUT /about_us/1.json
  def update
    respond_to do |format|
      if @about_u.update(about_u_params)
        format.html { redirect_to @about_u, notice: 'About u was successfully updated.' }
        format.json { render :show, status: :ok, location: @about_u }
      else
        format.html { render :edit }
        format.json { render json: @about_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /about_us/1
  # DELETE /about_us/1.json
  def destroy
    @about_u.destroy
    respond_to do |format|
      format.html { redirect_to about_us_url, notice: 'About u was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about_u
      @about_u = AboutU.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_u_params
      params.require(:about_u).permit(:name, :phone)
    end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/views/about_us/_form.html.erb
<%= form_for(@about_u) do |f| %>
  <% if @about_u.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about_u.errors.count, "error") %> prohibited this about_u from being saved:</h2>

      <ul>
      <% @about_u.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/about_us/edit.html.erb
<h1>Editing About Us</h1>

<%= render 'form' %>

<%= link_to 'Show', @about_u %> |
<%= link_to 'Back', about_us_path %>

app/views/about_us/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing About Us</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>&nbsp&nbsp&nbsp&nbsp&nbsp</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @about_us.each do |about_u| %>
      <tr>
        <td><%= about_u.name %></td>
        <th>&nbsp&nbsp&nbsp&nbsp&nbsp</th>
        <td><%= about_u.phone %></td>
        <th>&nbsp&nbsp&nbsp&nbsp&nbsp</th>
        <% if user_signed_in? %>
            <% if current_user.id===2 %>
        <td><%= link_to 'Show', about_u %></td>
        <th>&nbsp&nbsp&nbsp&nbsp&nbsp</th>
        <td><%= link_to 'Edit', edit_about_u_path(about_u) %></td>
        <th>&nbsp&nbsp&nbsp&nbsp&nbsp</th>
        <td><%= link_to 'Destroy', about_u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
  <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
    <% if current_user.id===2 %>
<%= link_to 'New About us', new_about_u_path %>
    <% end %>
<% end %>

app/views/about_us/new.html.erb
<h1>New About U</h1>

<%= render 'form' %>

<%= link_to 'Back', about_us_path %>

app/views/about_us/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @about_u.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @about_u.phone %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_about_u_path(@about_u) %> |
<% else %>
<% end %>
<%= link_to 'Back', about_us_path %>